const mongoose = require("mongoose");

const clientSchema = new mongoose.Schema(
  {
    brokerId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Broker",
      required: true,
      index: true,
    },
    fullName: { type: String, required: true, trim: true },
    clientCode: { type: String, required: true, trim: true, uppercase: true },
    idCode: { type: String, required: true, trim: true, uppercase: true },
    email: { type: String, trim: true, lowercase: true },
    phone: { type: String, trim: true },
    address: { type: String, trim: true },
    notes: { type: String, trim: true },
    kyc: {
      firstName: { type: String, trim: true },
      lastName: { type: String, trim: true },
      fatherName: { type: String, trim: true },
      dateOfBirth: { type: Date },
      gender: {
        type: String,
        enum: ["male", "female", "other", ""],
        default: "",
      },
      occupation: { type: String, trim: true },
      annualIncome: { type: String, trim: true },
      state: { type: String, trim: true },
      city: { type: String, trim: true },
      pincode: { type: String, trim: true },
      alternatePhone: { type: String, trim: true },
      preferredCommunication: { type: String, trim: true, default: "Email" },
      applicationDate: { type: Date },
      initialDeposit: { type: Number, default: 0 },
      aadhaarNumber: { type: String, trim: true },
      aadhaarVerified: { type: Boolean, default: false },
      aadhaarFrontUrl: { type: String, trim: true },
      aadhaarFrontPublicId: { type: String, trim: true },
      aadhaarBackUrl: { type: String, trim: true },
      aadhaarBackPublicId: { type: String, trim: true },
      aadhaarFilename: { type: String, trim: true },
      aadhaarSize: { type: Number },
      panNumber: { type: String, trim: true, uppercase: true },
      panVerified: { type: Boolean, default: false },
      panImageUrl: { type: String, trim: true },
      panImagePublicId: { type: String, trim: true },
      panFilename: { type: String, trim: true },
      panSize: { type: Number },
      mobileVerified: { type: Boolean, default: false },
      addressProofType: { type: String, trim: true, default: "Aadhaar Card" },
      addressProofUrl: { type: String, trim: true },
      addressProofPublicId: { type: String, trim: true },
      addressProofFilename: { type: String, trim: true },
      addressProofSize: { type: Number },
      bankProofType: { type: String, trim: true, default: "Bank Proof" },
      bankName: { type: String, trim: true },
      accountNumber: { type: String, trim: true },
      ifscCode: { type: String, trim: true, uppercase: true },
      bankAccountType: { type: String, trim: true, default: "Savings" },
      bankProofUrl: { type: String, trim: true },
      bankProofPublicId: { type: String, trim: true },
      bankProofFilename: { type: String, trim: true },
      bankProofSize: { type: Number },
      customerPhotoUrl: { type: String, trim: true },
      customerPhotoPublicId: { type: String, trim: true },
      customerSignatureUrl: { type: String, trim: true },
      customerSignaturePublicId: { type: String, trim: true },
      nationality: { type: String, trim: true, default: "Indian" },
      pep: { type: String, trim: true, default: "No" },
      sourceOfFunds: { type: String, trim: true, default: "Salary" },
      status: {
        type: String,
        enum: ["incomplete", "ready", "generated", "verified"],
        default: "incomplete",
      },
      referenceNumber: { type: String, trim: true, uppercase: true },
      generatedAt: { type: Date },
      submittedAt: { type: Date },
      verifiedAt: { type: Date },
      validTill: { type: Date },
      history: [
        {
          title: { type: String, trim: true },
          description: { type: String, trim: true },
          timestamp: { type: Date, default: Date.now },
          iconType: { type: String, trim: true },
        },
      ],
    },
    // Margin & account financial summary fields
    margin: {
      accountBalance: { type: Number, default: 0 },
      availableMargin: { type: Number, default: 0 },
      usedMargin: { type: Number, default: 0 },
      dpId: { type: String, trim: true, default: "12081600" },
    },
    segment: {
      type: String,
      enum: ["intraday", "delivery", "futures", "options", "commodity"],
      default: "intraday",
    },
    status: {
      type: String,
      enum: ["active", "inactive"],
      default: "active",
    },
  },
  { timestamps: true }
);

clientSchema.index({ brokerId: 1, clientCode: 1 }, { unique: true });
clientSchema.index({ brokerId: 1, idCode: 1 }, { unique: true });

module.exports = mongoose.model("Client", clientSchema);
